CREATE TABLE shifts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES companies(id),
    project_position_id bigint NOT NULL REFERENCES project_positions(id),
    created_by_user_id bigint NOT NULL REFERENCES app_users(id),
    mode varchar(20) NOT NULL CHECK (mode IN ('INDIVIDUAL','PUBLIC')),
    status varchar(20) NOT NULL CHECK (status IN ('OPEN','FULL','CANCELLED','EXPIRED')),
    shift_date date NOT NULL,
    start_time time NOT NULL,
    end_time time NOT NULL,
    capacity integer NOT NULL CHECK (capacity > 0),
    location varchar(255),
    notes varchar(1000),
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    CONSTRAINT ck_shift_time_order CHECK (end_time > start_time),
    CONSTRAINT ck_shift_mode_capacity CHECK ((mode = 'INDIVIDUAL' AND capacity = 1) OR mode = 'PUBLIC')
);
CREATE INDEX idx_shift_company_date ON shifts(company_id, shift_date);
CREATE INDEX idx_shift_company_status ON shifts(company_id, status);

CREATE TABLE shift_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id bigint NOT NULL REFERENCES shifts(id),
    worker_profile_id bigint NOT NULL REFERENCES worker_profiles(id),
    status varchar(20) NOT NULL CHECK (status IN ('PENDING','ACCEPTED','DECLINED','CANCELLED')),
    decline_reason varchar(500),
    responded_at timestamp,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    CONSTRAINT uk_shift_assignment_worker UNIQUE (shift_id, worker_profile_id)
);
CREATE INDEX idx_shift_assignment_worker_status ON shift_assignments(worker_profile_id,status);
