CREATE TABLE notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id bigint NOT NULL REFERENCES app_users(id),
    company_id bigint NOT NULL REFERENCES companies(id),
    type varchar(30) NOT NULL CHECK (type IN ('SHIFT_ASSIGNED','SHIFT_AVAILABLE','SHIFT_ACCEPTED','SHIFT_DECLINED','SHIFT_CANCELLED')),
    title varchar(160) NOT NULL,
    message varchar(1000) NOT NULL,
    target_path varchar(255) NOT NULL,
    related_shift_id bigint REFERENCES shifts(id),
    read_at timestamp,
    created_at timestamp NOT NULL
);
CREATE INDEX idx_notification_user_company_created ON notifications(app_user_id, company_id, created_at);
CREATE INDEX idx_notification_user_unread ON notifications(app_user_id, read_at);

CREATE TABLE notification_email_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id bigint NOT NULL REFERENCES notifications(id),
    recipient varchar(150) NOT NULL,
    subject varchar(200) NOT NULL,
    body varchar(5000) NOT NULL,
    status varchar(20) NOT NULL CHECK (status IN ('PENDING','SENT','FAILED')),
    attempts integer NOT NULL DEFAULT 0,
    next_attempt_at timestamp NOT NULL,
    last_error varchar(1000),
    sent_at timestamp,
    created_at timestamp NOT NULL
);
CREATE INDEX idx_notification_outbox_pending ON notification_email_outbox(status, next_attempt_at);
