CREATE TABLE password_reset_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id bigint NOT NULL REFERENCES app_users(id),
    token_hash varchar(64) NOT NULL UNIQUE,
    expires_at timestamp NOT NULL,
    used_at timestamp,
    created_at timestamp NOT NULL
);

CREATE INDEX idx_password_reset_tokens_user ON password_reset_tokens(app_user_id);
CREATE INDEX idx_password_reset_tokens_expiry ON password_reset_tokens(expires_at);
