--
-- PostgreSQL database dump
--

\restrict ZQdvbSWG6bMLaT1DQyQp368auqdXOPEax5StFFgaELDyquyv5diFE1Gdxkejdpc

-- Dumped from database version 17.10 (Debian 17.10-1.pgdg13+1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(150) NOT NULL,
    name character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    surname character varying(100),
    last_login_at timestamp(6) without time zone,
    status character varying(30) NOT NULL
);


--
-- Name: app_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: companies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.companies (
    id bigint NOT NULL,
    abn character varying(255) NOT NULL,
    active boolean,
    address character varying(255),
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: companies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.companies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_invitations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_invitations (
    id bigint NOT NULL,
    accepted_at timestamp(6) without time zone,
    cancelled_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(150) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    name character varying(100) NOT NULL,
    role character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    surname character varying(100) NOT NULL,
    token_hash character varying(64) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    company_id bigint NOT NULL,
    invited_by_user_id bigint NOT NULL,
    declined_at timestamp(6) without time zone,
    CONSTRAINT company_invitations_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'ADMIN'::character varying, 'MANAGER'::character varying, 'FINANCE'::character varying, 'WORKER'::character varying])::text[]))),
    CONSTRAINT company_invitations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'DECLINED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: company_invitations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company_invitations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_invitations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_join_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_join_links (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    current_uses integer NOT NULL,
    disabled_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone,
    max_uses integer,
    role character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    token_hash character varying(64) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    company_id bigint NOT NULL,
    created_by_user_id bigint NOT NULL,
    CONSTRAINT company_join_links_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'ADMIN'::character varying, 'MANAGER'::character varying, 'FINANCE'::character varying, 'WORKER'::character varying])::text[]))),
    CONSTRAINT company_join_links_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'EXPIRED'::character varying, 'DISABLED'::character varying])::text[])))
);


--
-- Name: company_join_links_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company_join_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_join_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_memberships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_memberships (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    role character varying(30) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    app_user_id bigint NOT NULL,
    company_id bigint NOT NULL,
    accepted_at timestamp(6) without time zone,
    rejected_at timestamp(6) without time zone,
    suspended_at timestamp(6) without time zone,
    status character varying(30) NOT NULL,
    CONSTRAINT company_memberships_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'ADMIN'::character varying, 'MANAGER'::character varying, 'FINANCE'::character varying, 'WORKER'::character varying])::text[])))
);


--
-- Name: company_memberships_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company_memberships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_memberships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_positions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_positions (
    id bigint NOT NULL,
    active boolean,
    created_at timestamp(6) without time zone,
    day_rate numeric(38,2),
    km_rate numeric(38,2),
    lafha_rate numeric(38,2),
    night_rate numeric(38,2),
    overtime_rate numeric(38,2),
    position_name character varying(100) NOT NULL,
    travel_time_rate numeric(38,2),
    updated_at timestamp(6) without time zone,
    weekend_rate numeric(38,2),
    project_id bigint NOT NULL
);


--
-- Name: project_positions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project_positions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_positions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_role_rate_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_role_rate_items (
    id bigint NOT NULL,
    active boolean NOT NULL,
    calculation_type character varying(30) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(200),
    rate_type character varying(50) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    value numeric(12,4) NOT NULL,
    project_role_rate_id bigint NOT NULL,
    CONSTRAINT project_role_rate_items_calculation_type_check CHECK (((calculation_type)::text = ANY ((ARRAY['BASE_RATE'::character varying, 'MULTIPLIER'::character varying, 'FIXED_RATE'::character varying, 'FIXED_AMOUNT'::character varying])::text[]))),
    CONSTRAINT project_role_rate_items_rate_type_check CHECK (((rate_type)::text = ANY ((ARRAY['REGULAR'::character varying, 'OVERTIME_1_5'::character varying, 'OVERTIME_2_0'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying, 'PUBLIC_HOLIDAY'::character varying, 'TRAVEL_TIME'::character varying, 'KILOMETRE'::character varying, 'LAFHA'::character varying])::text[])))
);


--
-- Name: project_role_rate_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project_role_rate_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_role_rate_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_role_rates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_role_rates (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    effective_from date NOT NULL,
    effective_to date,
    updated_at timestamp(6) without time zone NOT NULL,
    project_position_id bigint NOT NULL
);


--
-- Name: project_role_rates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project_role_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_role_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects (
    id bigint NOT NULL,
    active boolean,
    created_at timestamp(6) without time zone,
    description character varying(255),
    location character varying(255),
    name character varying(255),
    updated_at timestamp(6) without time zone,
    company_id bigint NOT NULL
);


--
-- Name: projects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_rates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_rates (
    id bigint NOT NULL,
    active boolean,
    day_rate numeric(38,2),
    km_rate numeric(38,2),
    lafha_rate numeric(38,2),
    night_rate numeric(38,2),
    overtime_rate numeric(38,2),
    role_name character varying(255),
    travel_time_rate numeric(38,2),
    weekend_rate numeric(38,2)
);


--
-- Name: role_rates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.role_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: work_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.work_logs (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    kilometres numeric(10,2) NOT NULL,
    lafha_nights integer NOT NULL,
    notes character varying(500),
    overtime_15_hours numeric(8,2) NOT NULL,
    overtime_20_hours numeric(8,2) NOT NULL,
    public_holiday_hours numeric(8,2) NOT NULL,
    regular_hours numeric(8,2) NOT NULL,
    saturday_hours numeric(8,2) NOT NULL,
    sunday_hours numeric(8,2) NOT NULL,
    travel_hours numeric(10,2) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    work_date date NOT NULL,
    project_position_id bigint NOT NULL,
    worker_profile_id bigint NOT NULL,
    status character varying(30) NOT NULL,
    submitted_at timestamp without time zone NOT NULL,
    approved_at timestamp without time zone,
    rejected_at timestamp without time zone,
    rejection_reason character varying(500),
    snapshot_company_name character varying(150),
    snapshot_gst_amount numeric(14,2),
    snapshot_kilometre_amount numeric(14,2),
    snapshot_kilometre_rate numeric(12,2),
    snapshot_lafha_amount numeric(14,2),
    snapshot_lafha_rate numeric(12,2),
    snapshot_overtime_15_amount numeric(14,2),
    snapshot_overtime_15_rate numeric(12,2),
    snapshot_overtime_20_amount numeric(14,2),
    snapshot_overtime_20_rate numeric(12,2),
    snapshot_position_name character varying(150),
    snapshot_project_name character varying(150),
    snapshot_public_holiday_amount numeric(14,2),
    snapshot_public_holiday_rate numeric(12,2),
    snapshot_regular_amount numeric(14,2),
    snapshot_regular_rate numeric(12,2),
    snapshot_saturday_amount numeric(14,2),
    snapshot_saturday_rate numeric(12,2),
    snapshot_subtotal_amount numeric(14,2),
    snapshot_sunday_amount numeric(14,2),
    snapshot_sunday_rate numeric(12,2),
    snapshot_total_amount numeric(14,2),
    snapshot_travel_amount numeric(14,2),
    snapshot_travel_rate numeric(12,2),
    snapshot_worker_abn character varying(11),
    snapshot_worker_gst_registered boolean,
    snapshot_worker_name character varying(200),
    manager_notes character varying(1000),
    finish_time time(0) without time zone,
    start_time time(0) without time zone,
    unpaid_break_minutes integer NOT NULL
);


--
-- Name: work_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.work_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.work_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: worker_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.worker_profiles (
    id bigint NOT NULL,
    abn character varying(11),
    bank_account_name character varying(150),
    bank_account_number character varying(20),
    bank_name character varying(100),
    bank_bsb character varying(6),
    created_at timestamp(6) without time zone NOT NULL,
    default_hourly_rate numeric(12,2),
    gst_registered boolean NOT NULL,
    notes character varying(1000),
    phone character varying(30),
    super_fund_name character varying(150),
    super_member_number character varying(100),
    super_usi character varying(50),
    updated_at timestamp(6) without time zone NOT NULL,
    app_user_id bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    status character varying(30) NOT NULL,
    CONSTRAINT worker_profiles_status_check CHECK (((status)::text = ANY ((ARRAY['INCOMPLETE'::character varying, 'COMPLETE'::character varying, 'SUSPENDED'::character varying])::text[])))
);


--
-- Name: worker_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.worker_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.worker_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_users app_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);


--
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- Name: company_invitations company_invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_invitations
    ADD CONSTRAINT company_invitations_pkey PRIMARY KEY (id);


--
-- Name: company_join_links company_join_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_join_links
    ADD CONSTRAINT company_join_links_pkey PRIMARY KEY (id);


--
-- Name: company_memberships company_memberships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_memberships
    ADD CONSTRAINT company_memberships_pkey PRIMARY KEY (id);


--
-- Name: project_positions project_positions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_positions
    ADD CONSTRAINT project_positions_pkey PRIMARY KEY (id);


--
-- Name: project_role_rate_items project_role_rate_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_role_rate_items
    ADD CONSTRAINT project_role_rate_items_pkey PRIMARY KEY (id);


--
-- Name: project_role_rates project_role_rates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_role_rates
    ADD CONSTRAINT project_role_rates_pkey PRIMARY KEY (id);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- Name: role_rates role_rates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_rates
    ADD CONSTRAINT role_rates_pkey PRIMARY KEY (id);


--
-- Name: companies uk56c9ob5wxtgfxja580w20ix7s; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT uk56c9ob5wxtgfxja580w20ix7s UNIQUE (abn);


--
-- Name: app_users uk_app_user_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT uk_app_user_email UNIQUE (email);


--
-- Name: company_invitations uk_invitation_token_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_invitations
    ADD CONSTRAINT uk_invitation_token_hash UNIQUE (token_hash);


--
-- Name: company_join_links uk_join_link_token_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_join_links
    ADD CONSTRAINT uk_join_link_token_hash UNIQUE (token_hash);


--
-- Name: company_memberships uk_membership_user_company; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_memberships
    ADD CONSTRAINT uk_membership_user_company UNIQUE (app_user_id, company_id);


--
-- Name: project_role_rates uk_position_rate_effective_from; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_role_rates
    ADD CONSTRAINT uk_position_rate_effective_from UNIQUE (project_position_id, effective_from);


--
-- Name: project_positions uk_project_position_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_positions
    ADD CONSTRAINT uk_project_position_name UNIQUE (project_id, position_name);


--
-- Name: project_role_rate_items uk_project_role_rate_item_type; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_role_rate_items
    ADD CONSTRAINT uk_project_role_rate_item_type UNIQUE (project_role_rate_id, rate_type);


--
-- Name: worker_profiles uk_worker_profile_abn; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worker_profiles
    ADD CONSTRAINT uk_worker_profile_abn UNIQUE (abn);


--
-- Name: worker_profiles uk_worker_profile_app_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worker_profiles
    ADD CONSTRAINT uk_worker_profile_app_user UNIQUE (app_user_id);


--
-- Name: companies ukqjgsqh1oq7xhof2tdte9l7e2b; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT ukqjgsqh1oq7xhof2tdte9l7e2b UNIQUE (email);


--
-- Name: work_logs work_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_logs
    ADD CONSTRAINT work_logs_pkey PRIMARY KEY (id);


--
-- Name: worker_profiles worker_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worker_profiles
    ADD CONSTRAINT worker_profiles_pkey PRIMARY KEY (id);


--
-- Name: idx_invitation_company_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invitation_company_status ON public.company_invitations USING btree (company_id, status);


--
-- Name: idx_invitation_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invitation_email ON public.company_invitations USING btree (email);


--
-- Name: idx_join_link_company_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_join_link_company_status ON public.company_join_links USING btree (company_id, status);


--
-- Name: idx_join_link_token_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_join_link_token_hash ON public.company_join_links USING btree (token_hash);


--
-- Name: idx_membership_company_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_membership_company_status ON public.company_memberships USING btree (company_id, status);


--
-- Name: idx_membership_user_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_membership_user_status ON public.company_memberships USING btree (app_user_id, status);


--
-- Name: idx_work_log_position_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_work_log_position_date ON public.work_logs USING btree (project_position_id, work_date);


--
-- Name: idx_work_log_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_work_log_status ON public.work_logs USING btree (status);


--
-- Name: idx_work_log_worker_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_work_log_worker_date ON public.work_logs USING btree (worker_profile_id, work_date);


--
-- Name: company_invitations fk_invitation_company; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_invitations
    ADD CONSTRAINT fk_invitation_company FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- Name: company_invitations fk_invitation_invited_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_invitations
    ADD CONSTRAINT fk_invitation_invited_by FOREIGN KEY (invited_by_user_id) REFERENCES public.app_users(id);


--
-- Name: company_join_links fk_join_link_company; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_join_links
    ADD CONSTRAINT fk_join_link_company FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- Name: company_join_links fk_join_link_created_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_join_links
    ADD CONSTRAINT fk_join_link_created_by FOREIGN KEY (created_by_user_id) REFERENCES public.app_users(id);


--
-- Name: company_memberships fk_membership_app_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_memberships
    ADD CONSTRAINT fk_membership_app_user FOREIGN KEY (app_user_id) REFERENCES public.app_users(id);


--
-- Name: company_memberships fk_membership_company; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_memberships
    ADD CONSTRAINT fk_membership_company FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- Name: work_logs fkdrwvebd96gua4x96pj98inn6x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_logs
    ADD CONSTRAINT fkdrwvebd96gua4x96pj98inn6x FOREIGN KEY (project_position_id) REFERENCES public.project_positions(id);


--
-- Name: work_logs fkfxtbwt052fiecs39ipw6iqi8q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_logs
    ADD CONSTRAINT fkfxtbwt052fiecs39ipw6iqi8q FOREIGN KEY (worker_profile_id) REFERENCES public.worker_profiles(id);


--
-- Name: project_role_rate_items fkphvvfnwj8e8lon2rmq2euk2gx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_role_rate_items
    ADD CONSTRAINT fkphvvfnwj8e8lon2rmq2euk2gx FOREIGN KEY (project_role_rate_id) REFERENCES public.project_role_rates(id);


--
-- Name: project_positions fkq2v0qo1fc2h4mbkgy15ejc93f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_positions
    ADD CONSTRAINT fkq2v0qo1fc2h4mbkgy15ejc93f FOREIGN KEY (project_id) REFERENCES public.projects(id);


--
-- Name: project_role_rates fkqtp1dxqj9o9tcupjc5xrl996s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_role_rates
    ADD CONSTRAINT fkqtp1dxqj9o9tcupjc5xrl996s FOREIGN KEY (project_position_id) REFERENCES public.project_positions(id);


--
-- Name: projects fkrvpjk20pqyytvj6m5cutub6iq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT fkrvpjk20pqyytvj6m5cutub6iq FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- Name: worker_profiles fks7sogakw9dkskcr2hmk4u1rg1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worker_profiles
    ADD CONSTRAINT fks7sogakw9dkskcr2hmk4u1rg1 FOREIGN KEY (app_user_id) REFERENCES public.app_users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict ZQdvbSWG6bMLaT1DQyQp368auqdXOPEax5StFFgaELDyquyv5diFE1Gdxkejdpc

